# Generated by Django 5.0.2 on 2024-02-12 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedHadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hadith')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_shared_by', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_shared_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surah_shared_by', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surah_shared_with', to=settings.AUTH_USER_MODEL)),
                ('surah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.surah')),
            ],
        ),
    ]
