# Generated by Django 5.0.2 on 2024-02-13 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sharedhadith_sharedsurah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdhikrread',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='userdhikrread',
            name='last_read',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 13, 30, 55, 931862, tzinfo=datetime.timezone.utc)),
        ),
    ]
